create or replace view  R_USERGROUPS as
  select USERGROUP.ID ,USERGROUP.CODE USERGROUP_CODE ,
  USERGROUP.NAME USERGROUP_NAME ,USERGROUP.REMARK USERGROUP_REMARK ,
 PERSON_UPD.ID PERSON_ID_UPD,
 PERSON_UPD.CODE PERSON_CODE_UPD,
 PERSON_UPD.NAME PERSON_NAME_UPD,
USERGROUP.UPDATE_IP USERGROUP_UPDATE_IP ,
USERGROUP.CREATED_AT USERGROUP_CREATED_AT ,
USERGROUP.UPDATED_AT USERGROUP_UPDATED_AT ,
USERGROUP.EXPIREDATE USERGROUP_EXPIREDATE 
from USERGROUPS USERGROUP ,PERSONS  PERSON_UPD 
where PERSON_UPD.ID = USERGROUP.PERSONS_ID_UPD 