source 'https://rubygems.org'

gem 'rails', '3.2.14'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'sqlite3'
gem 'rake','>10.0.3'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer', :platforms => :ruby

  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'

gem 'ruby-oci8'
gem 'memcache-client'
gem 'devise','3.0.0'
gem 'ruby-plsql'
gem 'git-rails'
gem 'activerecord-oracle_enhanced-adapter','1.4.2'

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
  gem 'debugger'
# gem 'ruby-debug'
##gem 'resque', :require => 'resque/server'
### plsql と相性が悪い　delayed_job 3.0.5 'delayed_job_active_record','0.4.4'
 gem 'delayed_job','3.0.4'
 gem 'delayed_job_active_record','0.3.3'
##gem 'daemon-spawn', :require => 'daemon_spawn'
 gem "daemons"
 gem "axlsx"
## gem "simple-spreadsheet"
##  gem 'roo'
 gem "rubyzip",'0.9.9'
 gem "rubyXL",'1.2.10'
## gem 'google-spreadsheet-ruby'
## gem 'simple_xlsx_reader'
### 普通にObjectをStoreしたい
### Dalli is a high performance pure Ruby client for accessing memcached servers.
gem 'dalli'
 gem 'prawn','0.12.0'
##gem 'prawn_rails'
###barcode code39,QR  ・・・・
gem 'barby'
gem 'prawn-qrcode'
gem 'clockwork'
gem 'whenever', :require => false
